import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Employee Management",
  description: "Generated by N@tcom",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
