import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Employee Management",
  description: "Generated by N@tcom",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className=""
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
